from pathlib import Path
p=Path('/tmp/anatomy/app/anatomy.ts'); s=p.read_text()
s=s.replace("export type SceneState = {inspectorOpen?:boolean;explode:number;visible:SystemId[];selected:string[];isolate:boolean;view:View;rotate:boolean;reset:number}","export type SceneState = {inspectorOpen?:boolean;explode:number;visible:SystemId[];selected:string[];hidden:string[];isolate:boolean;view:View;rotate:boolean;reset:number}")
s=s.replace(" 'spinalis thoracis':'The medial portion of the erector spinae. It extends the thoracic spine and helps maintain upright posture.',", " 'spinalis':'A deep medial erector-spinae muscle that extends the vertebral column and helps maintain upright posture.',\n 'spinalis thoracis':'The medial portion of the erector spinae. It extends the thoracic spine and helps maintain upright posture.',")
s=s.replace(" 'flexor carpi ulnaris':'A forearm muscle that flexes and adducts the wrist, contributing strongly to wrist stability and controlled hand movements.',", " 'flexor carpi ulnaris':'A forearm muscle that flexes and adducts the wrist, contributing strongly to wrist stability and controlled hand movements.',\n 'humeral head of flexor carpi ulnaris':'The humeral portion of flexor carpi ulnaris. It contributes to wrist flexion and adduction and helps stabilize the wrist.',\n 'ulnar head of flexor carpi ulnaris':'The ulnar portion of flexor carpi ulnaris. It contributes to wrist flexion and adduction and helps stabilize the wrist.',")
s=s.replace(" 'gastrocnemius':'The large two-headed calf muscle. It plantarflexes the ankle and also flexes the knee, contributing strongly to walking, running, and jumping.'\n};", " 'gastrocnemius':'The large two-headed calf muscle. It plantarflexes the ankle and also flexes the knee, contributing strongly to walking, running, and jumping.',\n 'medial head of gastrocnemius':'The medial head of the gastrocnemius. It plantarflexes the ankle and assists knee flexion during walking, running, and jumping.',\n 'lateral head of gastrocnemius':'The lateral head of the gastrocnemius. It plantarflexes the ankle and assists knee flexion while contributing to propulsion during gait.',\n 'head of gastrocnemius':'The two-headed gastrocnemius complex that plantarflexes the ankle and assists knee flexion.',\n 'head of biceps femoris':'The proximal portion of the biceps femoris complex, which contributes to hip extension and knee flexion.',\n 'head of muscle organ':'A grouped anatomical muscle region rather than a single named training muscle.',\n 'zone of muscle organ':'A grouped region of muscle tissue rather than a single named training muscle.'\n};")
s=s.replace("export function explanation(name:string,system:SystemId){\n const key=name.toLowerCase().replace(/^right |^left /,'');\n return EXPLANATIONS[key] ?? MUSCLE_EXPLANATIONS[key] ?? (system==='muscular' ? 'A skeletal muscle that generates force to produce movement, stabilize joints, and support posture.' : SYSTEMS.find(s=>s.id===system)?.description ?? '');\n}", "export function explanation(name:string,system:SystemId){\n let key=name.toLowerCase().replace(/^right |^left /,'').replace(/ muscle$/,'');\n return EXPLANATIONS[key] ?? MUSCLE_EXPLANATIONS[key] ?? (system==='muscular' ? 'A skeletal muscle that generates force to produce movement, stabilize joints, and support posture.' : SYSTEMS.find(s=>s.id===system)?.description ?? '');\n}")
p.write_text(s)

p=Path('/tmp/anatomy/app/page.tsx'); s=p.read_text()
s=s.replace("import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';", "import {Activity,ArrowUpRight,ChevronRight,EyeOff,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';")
s=s.replace("import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';", "import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';")
s=s.replace("const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};", "const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],hidden:[],isolate:false,view:'three-quarter',rotate:false,reset:0};")
s=s.replace(".then(data=>setAtlas(data as Atlas)).catch", ".then(data=>{\n   const raw=data as Atlas;\n   const allowedIds=new Set(raw.parts.filter(p=>p.system!=='connective'||p.name.toLowerCase().includes('calcaneal tendon')).map(p=>p.id));\n   const parts=raw.parts.filter(p=>allowedIds.has(p.id));\n   const concepts=raw.concepts.map(c=>({...c,elements:c.elements.filter(id=>allowedIds.has(id))})).filter(c=>c.elements.length>0);\n   setAtlas({...raw,parts,concepts});\n  }).catch")
s=s.replace("const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));", "const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,hidden:s.hidden.filter(id=>!c.elements.includes(id)),isolate:false,rotate:false}));")
s=s.replace("const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));", "const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],hidden:s.hidden.filter(x=>x!==id),isolate:false,rotate:false}));")
s=s.replace("const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));", "const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));")
# all / system show buttons should restore hidden muscles so hidden items remain recoverable without reset
s=s.replace("visible:activeSystems.map(x=>x.id)", "visible:activeSystems.map(x=>x.id),hidden:[]")
s=s.replace("visible:['skeletal']", "visible:['skeletal'],hidden:[]")
s=s.replace("visible:['muscular']", "visible:['muscular'],hidden:[]")
s=s.replace("visible:['connective']", "visible:['connective'],hidden:[]")
s=s.replace("visible:[s.id],isolate:false,selected:[]", "visible:[s.id],hidden:[],isolate:false,selected:[]")
# Add restore hidden button to panel foot
s=s.replace("<div className=\"panel-foot\"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant=\"ghost\" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>", "<div className=\"panel-foot\"><span>{visibleCount.toLocaleString()} pieces visible</span>{state.hidden.length>0&&<Button variant=\"ghost\" onClick={()=>setState(s=>({...s,hidden:[]}))}>Show hidden</Button>}<Button variant=\"ghost\" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>")
# Add hide action before clear
old="<Button variant=\"ghost\" className=\"secondary-action\" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button>"
new="{selected?.system==='muscular'&&<Button variant=\"ghost\" className=\"secondary-action\" onClick={()=>{setState(s=>({...s,hidden:Array.from(new Set([...s.hidden,...s.selected])),selected:[],isolate:false}));setDetails(false);}}><EyeOff size={17}/>Hide muscle</Button>}<Button variant=\"ghost\" className=\"secondary-action\" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button>"
s=s.replace(old,new)
p.write_text(s)
